module-name: nats-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/dev/nats-manager:PR-97
  - europe-docker.pkg.dev/kyma-project/prod/external/natsio/prometheus-nats-exporter:0.12.0
  - europe-docker.pkg.dev/kyma-project/prod/external/natsio/nats-server-config-reloader:0.11.0
  - europe-docker.pkg.dev/kyma-project/prod/external/natsio/nats-box:0.13.8
  - europe-docker.pkg.dev/kyma-project/prod/external/nats:v20230714-2.9.20-alpine3.18
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
