apiVersion: v1
kind: Service
metadata:
  name: manager-metrics
  labels:
    control-plane: nats-manager
    app.kubernetes.io/name: nats-manager
    app.kubernetes.io/instance: nats-manager
    app.kubernetes.io/component: nats-manager
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: http
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  selector:
    control-plane: nats-manager
    app.kubernetes.io/name: nats-manager
    app.kubernetes.io/instance: nats-manager
    app.kubernetes.io/component: nats-manager
  ports:
    - name: http-metrics
      protocol: TCP
      port: 80
      targetPort: 8080
